# Generated by Django 2.0.1 on 2018-02-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productimage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
