# Generated by Django 2.0.1 on 2018-02-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180210_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='pizza',
            field=models.ManyToManyField(to='products.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
