# Generated by Django 2.0.1 on 2018-02-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180214_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='pizza',
        ),
    ]
