# Generated by Django 2.0.1 on 2018-02-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_productimage_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
