# Generated by Django 2.0.1 on 2018-02-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20180214_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
