# Generated by Django 2.0.1 on 2018-02-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20180214_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='currency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
